name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "30 18 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: half-year
        uses: lowlighter/metrics@latest
        with:
          filename: assets/yearly_details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: assets/detail_lang.svg
          template: terminal
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, metadata
          plugin_languages: yes
          plugin_languages_ignored: >-
            less, dockerfile, makefile, qmake, lex, cmake,    gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 5
