name: WakaTime Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          COMMIT_MESSAGE: Update Waka_api stats
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LANGUAGE: "True"
          SHOW_TIMEZONE: "False"
          SHOW_SHORT_INFO: "False"
          SYMBOL_VERSION: 3
          

      # - uses: athul/waka-readme@8539bedb8277066fc9fe1b47d1f9b108eb866494
      #   with:
      #     WAKATIME_API_KEY: ${{ secrets.WAKAPI_API_KEY }}
      #     COMMIT_MESSAGE: Update Waka_api stats
      #     #IGNORED_LANGUAGES: YAML JSON TOML
      #     BLOCKS: "â¬œðŸŸ¨ðŸŸ©"
      #     TIME_RANGE: last_30_days
      #     SHOW_TIME: true